name: flutter_pay
description: Flutter plugin that help you make payments through Apple and Google Pay
version: 0.10.0
homepage: https://github.com/xamelon/flutter_pay

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.2.3
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.xamelon.flutter_pay
    pluginClass: FlutterPayPlugin
